### ISSUE TITLE
daovm.net no longer owned by this project

### ISSUE THREAD

**Issue by funny-falcon** [daokoder/dao#526] opened 2016-08-29 14:09 UTC

**Comment by dumblob** [comment] 2016-08-29 18:29
Duplicate of https://github.com/daokoder/dao/issues/517 .

**Comment by funny-falcon** [comment] 2016-08-29 21:03
so, why you didn't launch other website and didn't fix url in documentation and repository description?

**Comment by dumblob** [comment] 2016-09-05 22:24
@funny-falcon thanks for reaching out. For such important things we obeyed the rule to first get @daokoder's permission as he needed to have full control over all the main Dao channels.

Now @daokoder appeared online again after almost a year, so I hoped he'll express his opinion on this. Anyway, I currently do not have commit access to this repository, i.e. to documentation (not even @Night-walker does if I'm not mistaken, so we can actually only issue a "blind" pull request).

**Comment by daokoder** [comment] 2016-10-12 15:13
Now the new website is at http://daoscript.org.

**Closed** 2016-10-12 15:13 UTC
